// React/04. Routing/react-my-pet/src/components/Register.js
export function Register() {
    return (
        <section className="register">
            <form action="#" method="post">
                <fieldset>
                    <legend>Register</legend>
                    <p className="field">
                        <label htmlFor="username">Username</label>
                        <span className="input">
                            <input type="text" name="username" id="username" placeholder="Username" />
                            <span className="actions"></span>
                            <i className="fas fa-user"></i>
                        </span>
                    </p>
                    <p className="field">
                        <label htmlFor="password">Password</label>
                        <span className="input">
                            <input type="password" name="password" id="password" placeholder="Password" />
                            <span className="actions"></span>
                            <i className="fas fa-key"></i>
                        </span>
                    </p>
                    <input className="button submit" type="submit" value="Register" />
                </fieldset>
            </form>
        </section>
    );
}

// Angular/SoftUni-Forum/client/softuni-forum/src/app/user/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from '../user.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {

  constructor(private userService: UserService) {}

  register(email: string, password: string) {
    this.userService.register({ email, password });
  }
}

<form class="register" action="" method="post">

    <fieldset>
        <h2>Registration Form</h2>

        <!-- username -->
        <p class="field field-icon">
            <label for="username"><span><i class="fas fa-user"></i></span></label>
            <input class="input-error" type="text" name="username" id="username" placeholder="Johny">
        </p>
        <!-- <p class="error">
            Username is required!
        </p> -->

        <!-- email -->
        <p class="field field-icon">
            <label for="email"><span><i class="fas fa-envelope"></i></span></label>
            <input type="email" name="email" id="email" placeholder="john.doe@gmail.com">
        </p>
        <!-- <p class="error">
            Email is required!
        </p>
        <p class="error">
            Email is not valid!
        </p> -->

        <!-- telephone -->
        <p class="field field-icon">
            <label for="tel"><span><i class="fas fa-phone"></i></span></label>
            <select name="select-tel" id="select-tel" class="tel">
                <option value="00359">+359</option>
            </select>
            <input type="text" name="tel" id="tel" placeholder="885 888 888">
        </p>

        <!-- password -->
        <p class="field field-icon">
            <label for="password"><span><i class="fas fa-lock"></i></span></label>
            <input type="password" name="password" id="password" placeholder="******">
        </p>
        <!-- <p class="error">
            Password is required!
        </p>
        <p class="error">
            Password must be at least 4 characters!
        </p> -->

        <!-- rePassword -->
        <p class="field field-icon">
            <label for="rePassword"><span><i class="fas fa-lock"></i></span></label>
            <input type="password" name="rePassword" id="rePassword" placeholder="******">
        </p>
        <!-- <p class="error">Repeat Password does not match password!</p> -->

        <button disabled>Create Account</button>

        <p class="text-center">
            Have an account?
            <a href="#">Log In</a>
        </p>

    </fieldset>
</form>
