// Angular/SoftUni-Forum/client/softuni-forum/src/app/user/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../user.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  constructor(
    private userService: UserService,
    private router: Router) {}

  login(email: HTMLInputElement, password: HTMLInputElement) {
    this.userService.login(email.value, password.value);
    email.value = '';
    password.value = '';
    this.router.navigate(['/home']);
  }
}

<form class="login" action="" method="post">

    <fieldset>
        <h2>Login Form</h2>

        <p class="field field-icon">
            <label for="email"><span><i class="fas fa-envelope"></i></span></label>
            <input #emailInput class="input-error" type="email" name="email" id="email" placeholder="john.doe@gmail.com">
        </p>
        <!-- <p class="error">
            Email is required!
        </p> -->
        <!-- <p class="error">
            Email is not valid!
        </p> -->

        <p class="field field-icon">
            <label for="password"><span><i class="fas fa-lock"></i></span></label>
            <input #passwordInput type="password" name="password" id="password" placeholder="******">
        </p>
        <!-- <p class="error">
            Password is required!
        </p>
        <p class="error">
            Password must be at least 4 characters!
        </p> -->

        <button (click)="login(emailInput, passwordInput)">Login</button>

        <p class="text-center">
            Have an account?
            <a href="#">Register</a>
        </p>

    </fieldset>
</form>

// React/04. Routing/react-my-pet/src/components/Login.js
export function Login() {
    return (
        <section className="login">
            <form action="#" method="post">
                <fieldset>
                    <legend>Login</legend>
                    <p className="field">
                        <label htmlFor="username">Username</label>
                        <span className="input">
                            <input type="text" name="username" id="username" placeholder="Username" />
                            <span className="actions"></span>
                            <i className="fas fa-user"></i>
                        </span>
                    </p>
                    <p className="field">
                        <label htmlFor="password">Password</label>
                        <span className="input">
                            <input type="password" name="password" id="password" placeholder="Password" />
                            <span className="actions"></span>
                            <i className="fas fa-key"></i>
                        </span>
                    </p>
                    <input className="button submit" type="submit" value="Login" />
                </fieldset>
            </form>
        </section>
    );
}
